### ISSUE TITLE
Macro Key Support.

### ISSUE THREAD

**Issue by wherkamp** [FiercestT/corsair-cue-java#1]
I am curious  if their is a way to detect the press of a macro key?

**Comment by FiercestT** [comment]
The source SDK has a callback on receiving input from a specific key id (which should include macros). Though this wrapper doesn't support it yet as it's primary purpose was to support lighting. I do see the potential for macroing light effects, i'll look into updating the Library and frontend wrapper.

**Comment by wherkamp** [comment]
Awesome, I am currently writing a video game in Java and I was wanting to get support for the Macro Keys on Corsair Keyboards.

**Comment by FiercestT** [comment]
Apologies for the wait, I have done an overhaul of the SDK and added macro key support. Thanks!
