### ISSUE TITLE
sdk.getLedPositions() don't work.

### ISSUE THREAD

**Issue by Neptnium** [FiercestT/corsair-cue-java#3]
I have a problem, sdk.getLedPositions() does not exists, it is replaced by sdk.getLedPostitions() and sdk.getLedPostitions() calls null pointer :
Exception in thread "main" java.lang.NullPointerException
	at ca.fiercest.cuesdk.CueSDK.getLedPostitions(CueSDK.java:127)
Can you help me please ?
Andsorry for my english if it's bad.

**Comment by FiercestT** [comment]
[Resolved]

This error occurs when the Corsair Server (ICUE app) is not running, meaning the SDK cannot actually do anything unless ICUE is running.
This was resolved by throwing a NoServerException on the CueSDK constructor. You will now get an error that you can handle with a try/catch if there is no server detected. 
Thank you for bringing this up

Example
```java
CueSDK sdk;
try {
	sdk = CueSDK(true);
}
catch(NoServerException ex) {
	System.out.println("No server found, cannot connect to corsair just yet.");
}
```
